services:
  pedido-db:
    image: postgres:15
    container_name: pedido_db
    environment:
      POSTGRES_DB: pedido_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"          # Porta externa diferente para evitar conflito
    volumes:
      - pedido_pgdata:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_pedido
    ports:
      - "5673:5672"          # Porta AMQP ajustada para evitar conflito
      - "15673:15672"        # Painel web também ajustado
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  pedido-service:
    build:
      context: .
    container_name: pedido_service
    ports:
      - "8082:8080"          # Porta para expor API do pedido-service
      - "5006:5006"
    depends_on:
      - pedido-db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pedido-db:5432/pedido_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      _JAVA_OPTIONS: >
        -Xdebug 
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    restart: always

volumes:
  pedido_pgdata:

networks:
  default:
    name: 7adjt-shopsphere-ms-pedido-service_default
    external: true